### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sims143**
Added the required screenshots for documentation.

### CODE REVIEW

**Comment by jtmelton** [comment]
@sims143 I can't depend on a separate repo remaining alive for our documentation. If you want to add the screenshots as a directory under this repo, I'd be happy to merge.

**Comment by sims143** [comment]
Hello John, I don't have access to upload files to repository. Its prompting the below message when I tried to upload files. 

"Uploads are disabled.
File uploads require push access to this repository."

**Comment by jtmelton** [comment]
Ok, maybe send me the files and I can upload them to the directory, then you can make the changes?

**Comment by sims143** [comment]
Files sent to your mail.

**Comment by jtmelton** [comment]
@sims143 Ok, uploaded screenshots to https://github.com/jtmelton/appsensor/tree/master/integrations/elk-stack-documentation/screenshots

**Comment by jtmelton** [comment]
Closed due to https://github.com/jtmelton/appsensor/pull/45

**Pull request closed without merging**
